# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

linters:
  disable-all: true
  enable:
    - golint
    - lll
    - unused

linters-settings:
  lll:
    line-length: 200
    tab-width: 1
