#!/usr/bin/env bash

git secrets --pre_commit_hook -- "$@"

go mod tidy

git diff --quiet --exit-code go.mod go.sum

if [ ${?} -eq 1 ]; then
  echo 'module files has been changed'
  echo 'please re-commit module files'

  exit 1
fi

go_files=$(git diff --name-only --staged | grep '.go$')

if [ ! -z "${go_files}" ]; then
  make build
fi
